spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/service?serverTimezone=UTC}
    username: ${DB_USERNAME:Koria}
    password: ${DB_PASSWORD}

  flyway:
    url: ${DB_URL:jdbc:mysql://localhost:3306/service?serverTimezone=UTC}
    user: ${DB_USERNAME:Koria}
    password: ${DB_PASSWORD}
    enabled: true
    schemas: public
    locations: classpath:db/migration
